site_name: DataOrc Documentation
site_description: Unified documentation for DataOrc packages
site_url: https://equinor.github.io/dataorc/
repo_url: https://github.com/equinor/dataorc
repo_name: equinor/dataorc
edit_uri: edit/main/docs/

theme:
  name: material
  logo: assets/logo.png  # Path to your logo file
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      accent: green
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      accent: green
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.highlight
    - search.suggest

plugins:
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true
  - macros:
      modules:
        - docs.macros

markdown_extensions:
  - admonition
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Changelogs: changelogs.md

extra_javascript:
  - assets/changelog/filter.js
extra_css:
  - assets/changelog/styles.css
