site_name: DataOrc Documentation
site_description: Unified documentation for DataOrc packages
site_url: https://equinor.github.io/dataorc/
repo_url: https://github.com/equinor/dataorc
repo_name: equinor/dataorc
edit_uri: edit/main/docs/

theme:
  name: material
  logo: assets/logo.png  # Path to your logo file
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      accent: green
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      accent: green
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.highlight
    - search.suggest

plugins:
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  # Enable the Snippets extension to add the ability to embed content from
  # external files.
  # Ref: https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#snippets
  - pymdownx.highlight:
      anchor_linenums: true
      linenums_style: table
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets

nav:
  - Home: index.md
  - User guide:
    - Packages:
      - dataorc-utils:
        - Config:
          - Overview: packages/dataorc-utils/config/index.md
          - CorePipelineConfig: packages/dataorc-utils/config/core_pipeline_config.md
          - PipelineParameterManager: packages/dataorc-utils/config/pipeline_parameter_manager.md
          - Defaults and validation: packages/dataorc-utils/config/defaults_and_validation.md
  - Changelog:
    - dataorc: changelog/index.md
    - dataorc-utils: changelog/dataorc-utils.md
